version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      - DB_CONNECTION_STRING=postgresql://hw:hw@db:5432/hw
      - DB_PASSWORD=hw
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=hw
      - REDIS_USERNAME=hw
      - REDIS_DB=0
    networks:
      - app-network

  redis:
    image: redis:7.2.4
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=hw
      - REDIS_USERNAME=hw
    volumes:
      - redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    networks:
      - app-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hw
      - POSTGRES_USER=hw
      - POSTGRES_PASSWORD=hw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis-data: