version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - DB_CONNECTION_STRING=postgresql://hw:hw@db:5432/hw
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=hw
      - DB_USER=hw
      - DB_PASSWORD=hw
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hw
      - POSTGRES_USER=hw
      - POSTGRES_PASSWORD=hw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: